# Generated by Django 3.0 on 2019-12-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('enrollment_year', models.DateField(verbose_name='入学时间')),
            ],
            options={
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Courlas',
            fields=[
                ('courlas_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('term', models.DateField(verbose_name='学期')),
                ('syllabus', models.CharField(max_length=15)),
                ('time_location', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'Courlas',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('credit', models.PositiveIntegerField()),
                ('syllabus', models.CharField(max_length=15)),
                ('is_partly_visible', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
                ('phase', models.IntegerField()),
                ('beg_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Phase',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'School',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(choices=[('1', '大一'), ('2', '大二'), ('3', '大三'), ('4', '大四')], max_length=1)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=2)),
                ('title', models.CharField(choices=[('Instructor', '讲师'), ('Assitant', '助理教授'), ('Associate', '副教授'), ('Professor', '教授')], default='Instructor', max_length=15)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.School')),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('character', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '教秘'), ('superadmin', '管理员')], max_length=12)),
                ('x_no', models.CharField(max_length=12)),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='TeacherCourlas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courlas_no', models.ManyToManyField(to='qqa.Courlas')),
                ('teacher_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Teacher')),
            ],
            options={
                'db_table': 'TeacherCourlas',
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Class')),
                ('student_no', models.ManyToManyField(to='qqa.Student')),
            ],
            options={
                'db_table': 'StudentClass',
            },
        ),
        migrations.CreateModel(
            name='SelectRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_grade', models.CharField(max_length=12)),
                ('submit_time', models.DateTimeField()),
                ('phase', models.CharField(max_length=12)),
                ('intention', models.IntegerField()),
                ('courlas_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Courlas')),
                ('student_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Student')),
            ],
            options={
                'db_table': 'SelectRecord',
            },
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('admin_no', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('admin_name', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.School', unique=True)),
            ],
            options={
                'db_table': 'SchoolAdmin',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('course_type', models.CharField(choices=[('ZYBX', '专业必修'), ('ZYXX', '专业选修'), ('QXGT', '全校共同课'), ('XKJC', '学科基础')], max_length=6)),
                ('semester', models.CharField(max_length=10)),
                ('course_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Course')),
            ],
            options={
                'db_table': 'Program',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=20)),
                ('school_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.School')),
            ],
            options={
                'db_table': 'Major',
            },
        ),
        migrations.AddField(
            model_name='courlas',
            name='course_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Course'),
        ),
        migrations.AddField(
            model_name='class',
            name='major_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Major'),
        ),
        migrations.CreateModel(
            name='StudentCourlas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('intention', models.IntegerField()),
                ('courlas_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Courlas')),
                ('student_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Student')),
            ],
            options={
                'db_table': 'StudentCourlas',
                'unique_together': {('student_no', 'courlas_no', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='PartlyVisible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Class')),
                ('courlas_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Courlas')),
            ],
            options={
                'db_table': 'PartlyVisible',
                'unique_together': {('courlas_no', 'class_no')},
            },
        ),
        migrations.CreateModel(
            name='MajorProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Major')),
                ('program_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Program')),
            ],
            options={
                'db_table': 'MajorProgram',
                'unique_together': {('major_no', 'program_no')},
            },
        ),
        migrations.CreateModel(
            name='ClassMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Class')),
                ('major_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Major')),
            ],
            options={
                'db_table': 'ClassMajor',
                'unique_together': {('class_no', 'major_no')},
            },
        ),
    ]
