# Generated by Django 3.0 on 2019-12-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_no', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ZYBX', '专业必修'), ('ZYXX', '专业选修')], max_length=4)),
                ('course_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
