# Generated by Django 3.0 on 2020-01-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qqa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courlas',
            name='courlas_name',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='courlas',
            name='max_select_num',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='courlas',
            name='selected_num',
            field=models.IntegerField(default=0),
        ),
    ]
