# Generated by Django 3.0 on 2019-12-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qqa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmin',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
