# Generated by Django 2.2.6 on 2019-12-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qqa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='character',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '教秘')], max_length=7),
        ),
    ]
