# Generated by Django 3.0 on 2019-12-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qqa', '0002_auto_20191221_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='type',
            new_name='course_type',
        ),
    ]
