# Generated by Django 3.0 on 2020-01-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qqa', '0002_auto_20191231_2023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectrecord',
            unique_together={('student_no', 'courlas_no', 'student_grade')},
        ),
    ]
