# Generated by Django 3.0 on 2019-12-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qqa', '0003_auto_20191221_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
