# Generated by Django 2.2.6 on 2019-12-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qqa', '0004_course_course_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SC',
            new_name='StudentCourse',
        ),
        migrations.RenameModel(
            old_name='TC',
            new_name='TeacherCourse',
        ),
    ]
