# Generated by Django 2.2.6 on 2019-12-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qqa', '0005_auto_20191221_1710'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentcourse',
            table='StudentCourse',
        ),
        migrations.AlterModelTable(
            name='teachercourse',
            table='TeacherCourse',
        ),
    ]
