# Generated by Django 2.2.6 on 2019-12-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qqa', '0007_auto_20191221_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqa.Student'),
        ),
    ]
